<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-10-17 23:52:26.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\VotacionBundle\Entity\Curso
 *
 * @ORM\Entity()
 * @ORM\Table(name="Curso")
 */
class Curso
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    protected $Curso;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $Laboratorio;

    /**
     * @ORM\OneToMany(targetEntity="PensumAnio", mappedBy="curso")
     * @ORM\JoinColumn(name="id", referencedColumnName="Curso_id")
     */
    protected $pensumAnios;

    public function __construct()
    {
        $this->pensumAnios = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\Curso
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Curso.
     *
     * @param string $Curso
     * @return \Umg\VotacionBundle\Entity\Curso
     */
    public function setCurso($Curso)
    {
        $this->Curso = $Curso;

        return $this;
    }

    /**
     * Get the value of Curso.
     *
     * @return string
     */
    public function getCurso()
    {
        return $this->Curso;
    }

    /**
     * Set the value of Laboratorio.
     *
     * @param boolean $Laboratorio
     * @return \Umg\VotacionBundle\Entity\Curso
     */
    public function setLaboratorio($Laboratorio)
    {
        $this->Laboratorio = $Laboratorio;

        return $this;
    }

    /**
     * Get the value of Laboratorio.
     *
     * @return boolean
     */
    public function getLaboratorio()
    {
        return $this->Laboratorio;
    }

    /**
     * Add PensumAnio entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\PensumAnio $pensumAnio
     * @return \Umg\VotacionBundle\Entity\Curso
     */
    public function addPensumAnio(PensumAnio $pensumAnio)
    {
        $this->pensumAnios[] = $pensumAnio;

        return $this;
    }

    /**
     * Remove PensumAnio entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\PensumAnio $pensumAnio
     * @return \Umg\VotacionBundle\Entity\Curso
     */
    public function removePensumAnio(PensumAnio $pensumAnio)
    {
        $this->pensumAnios->removeElement($pensumAnio);

        return $this;
    }

    /**
     * Get PensumAnio entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPensumAnios()
    {
        return $this->pensumAnios;
    }

    public function __sleep()
    {
        return array('id', 'Curso', 'Laboratorio');
    }
    
    public function __toString()
    {
        return $this->Curso;
    }
    

}