<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-10-17 23:52:26.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Umg\VotacionBundle\Entity\Seccion
 *
 * @ORM\Entity()
 * @ORM\Table(name="Seccion", indexes={@ORM\Index(name="fk_Seccion_Semestre1_idx", columns={"Semestre_id"})})
 */
class Seccion
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $Seccion;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Semestre_id;

    /**
     * @ORM\ManyToOne(targetEntity="Semestre", inversedBy="seccions")
     * @ORM\JoinColumn(name="Semestre_id", referencedColumnName="id")
     */
    protected $semestre;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\Seccion
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Seccion.
     *
     * @param string $Seccion
     * @return \Umg\VotacionBundle\Entity\Seccion
     */
    public function setSeccion($Seccion)
    {
        $this->Seccion = $Seccion;

        return $this;
    }

    /**
     * Get the value of Seccion.
     *
     * @return string
     */
    public function getSeccion()
    {
        return $this->Seccion;
    }

    /**
     * Set the value of Semestre_id.
     *
     * @param integer $Semestre_id
     * @return \Umg\VotacionBundle\Entity\Seccion
     */
    public function setSemestreId($Semestre_id)
    {
        $this->Semestre_id = $Semestre_id;

        return $this;
    }

    /**
     * Get the value of Semestre_id.
     *
     * @return integer
     */
    public function getSemestreId()
    {
        return $this->Semestre_id;
    }

    /**
     * Set Semestre entity (many to one).
     *
     * @param \Umg\VotacionBundle\Entity\Semestre $semestre
     * @return \Umg\VotacionBundle\Entity\Seccion
     */
    public function setSemestre(Semestre $semestre = null)
    {
        $this->semestre = $semestre;

        return $this;
    }

    /**
     * Get Semestre entity (many to one).
     *
     * @return \Umg\VotacionBundle\Entity\Semestre
     */
    public function getSemestre()
    {
        return $this->semestre;
    }

    public function __sleep()
    {
        return array('id', 'Seccion', 'Semestre_id');
    }
}