<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-10-18 12:23:28.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\VotacionBundle\Entity\Semestre
 *
 * @ORM\Entity()
 * @ORM\Table(name="Semestre", indexes={@ORM\Index(name="fk_Semestre_CampusCarrera1_idx", columns={"CampusCarrera_id"})})
 */
class Semestre
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $Semestre;

    /**
     * @ORM\Column(type="integer")
     */
    protected $CampusCarrera_id;

    /**
     * @ORM\OneToMany(targetEntity="CarreraCurso", mappedBy="semestre")
     * @ORM\JoinColumn(name="id", referencedColumnName="Semestre_id")
     */
    protected $carreraCursos;

    /**
     * @ORM\OneToMany(targetEntity="Seccion", mappedBy="semestre")
     * @ORM\JoinColumn(name="id", referencedColumnName="Semestre_id")
     */
    protected $seccions;

    /**
     * @ORM\ManyToOne(targetEntity="CampusCarrera", inversedBy="semestres")
     * @ORM\JoinColumn(name="CampusCarrera_id", referencedColumnName="id")
     */
    protected $campusCarrera;

    public function __construct()
    {
        $this->carreraCursos = new ArrayCollection();
        $this->seccions = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\Semestre
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Semestre.
     *
     * @param string $Semestre
     * @return \Umg\VotacionBundle\Entity\Semestre
     */
    public function setSemestre($Semestre)
    {
        $this->Semestre = $Semestre;

        return $this;
    }

    /**
     * Get the value of Semestre.
     *
     * @return string
     */
    public function getSemestre()
    {
        return $this->Semestre;
    }

    /**
     * Set the value of CampusCarrera_id.
     *
     * @param integer $CampusCarrera_id
     * @return \Umg\VotacionBundle\Entity\Semestre
     */
    public function setCampusCarreraId($CampusCarrera_id)
    {
        $this->CampusCarrera_id = $CampusCarrera_id;

        return $this;
    }

    /**
     * Get the value of CampusCarrera_id.
     *
     * @return integer
     */
    public function getCampusCarreraId()
    {
        return $this->CampusCarrera_id;
    }

    /**
     * Add CarreraCurso entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\CarreraCurso $carreraCurso
     * @return \Umg\VotacionBundle\Entity\Semestre
     */
    public function addCarreraCurso(CarreraCurso $carreraCurso)
    {
        $this->carreraCursos[] = $carreraCurso;

        return $this;
    }

    /**
     * Remove CarreraCurso entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\CarreraCurso $carreraCurso
     * @return \Umg\VotacionBundle\Entity\Semestre
     */
    public function removeCarreraCurso(CarreraCurso $carreraCurso)
    {
        $this->carreraCursos->removeElement($carreraCurso);

        return $this;
    }

    /**
     * Get CarreraCurso entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCarreraCursos()
    {
        return $this->carreraCursos;
    }

    /**
     * Add Seccion entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\Seccion $seccion
     * @return \Umg\VotacionBundle\Entity\Semestre
     */
    public function addSeccion(Seccion $seccion)
    {
        $this->seccions[] = $seccion;

        return $this;
    }

    /**
     * Remove Seccion entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\Seccion $seccion
     * @return \Umg\VotacionBundle\Entity\Semestre
     */
    public function removeSeccion(Seccion $seccion)
    {
        $this->seccions->removeElement($seccion);

        return $this;
    }

    /**
     * Get Seccion entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSeccions()
    {
        return $this->seccions;
    }

    /**
     * Set CampusCarrera entity (many to one).
     *
     * @param \Umg\VotacionBundle\Entity\CampusCarrera $campusCarrera
     * @return \Umg\VotacionBundle\Entity\Semestre
     */
    public function setCampusCarrera(CampusCarrera $campusCarrera = null)
    {
        $this->campusCarrera = $campusCarrera;

        return $this;
    }

    /**
     * Get CampusCarrera entity (many to one).
     *
     * @return \Umg\VotacionBundle\Entity\CampusCarrera
     */
    public function getCampusCarrera()
    {
        return $this->campusCarrera;
    }

    public function __sleep()
    {
        return array('id', 'Semestre', 'CampusCarrera_id');
    }
}